### ISSUE TITLE
Package name and registration

### ISSUE THREAD

**Issue by giordano** [matteobachetti/psrsearch.jl#6]
In case you later wanted to register the package in the [General](https://github.com/JuliaRegistries/General) registry (the default one), note that by convention Julia packages use CamelCase, contrary to the Python ecosystem which prefers lowercase.  Thus, a more standard name would probably be something like `PSResearch`.  Also, note that abbreviations are somewhat discouraged.

When you'll want to register the package, the workflow is as follows:
* use either the GitHub app [JuliaRegistrator](https://github.com/JuliaRegistries/Registrator.jl) (this is already setup for all repositories of this organisation) or [JuliaHub](https://juliahub.com/ui/Home) to request the registration of the package
* a new pull request will be automatically opened in [General](https://github.com/JuliaRegistries/General)
* a bot will check whether the package meets all [requisites](https://github.com/JuliaRegistries/General/blob/5de192f85b2d05597ba62560606db36b78f449a5/README.md#automatic-merging-of-pull-requests), if so the pull request will be automatically merged after 3 days
* after successful registration of the package and any new version, [TagBot](https://github.com/JuliaRegistries/TagBot) will automatically create a git tag and GitHub release in this repository, corresponding to the version that appear in the General registry.  It is important to _not_ create the git tag before registration: from time to time it happens that one needs to do some fixes (e.g., missing compat bounds in the `Project.toml` file).  TagBot, instead, will ensure the git tag is consistent with the version actually present in the registry.

**Comment by matteobachetti** [comment]
@giordano looks like everything works now! Closing, feel free to reopen if I missed something.
